### ISSUE TITLE
gdown version must be upgraded to latest

### ISSUE THREAD

**Issue by Luca-Calabria** [mlcommons/training_results_v2.1#12]
Hi, I experienced problems with data downloading using gdown 
```
root@6f7d7dcb8810:/workspace/bert# ./input_preprocessing/prepare_data.sh --outputdir /workspace/bert_data
Preparing Mlperf BERT dataset in /workspace/bert_data
Traceback (most recent call last):
  File "/opt/conda/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/gdown/cli.py", line 150, in main
    filename = download(
  File "/opt/conda/lib/python3.8/site-packages/gdown/download.py", line 199, in download
    filename_from_url = m.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "/opt/conda/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/gdown/cli.py", line 150, in main
    filename = download(
  File "/opt/conda/lib/python3.8/site-packages/gdown/download.py", line 199, in download
    filename_from_url = m.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
Traceback (most recent call last):
  File "/opt/conda/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/gdown/cli.py", line 150, in main
    filename = download(
  File "/opt/conda/lib/python3.8/site-packages/gdown/download.py", line 199, in download
    filename_from_url = m.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=14xV2OUGSQDG_yDBrmbSdcDC-QGeqpfs_ 
```

I solved it upgrading version to latest 
```pip install --upgrade gdown```

This file needs to be updated https://github.com/mlcommons/training_results_v2.1/blob/main/NVIDIA/benchmarks/bert/implementations/pytorch-22.09/requirements.txt#L3 

Thanks!

**Comment by lawrence910426** [comment]
For me, I had manually downloaded the files instead of directly `gdown` it.
