### ISSUE TITLE
Running the resnet50 docker file gives the following error for Nvidia implementation

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/training_results_v2.1#3]
I was following [this](https://github.com/mlcommons/training_results_v2.1/tree/main/NVIDIA/benchmarks/resnet/implementations/mxnet-22.04) README and everything went fine until the traning start using docker container which is giving the below error. 

```
:::MLLOG {"namespace": "", "time_ms": 1684162286280, "event_type": "POINT_IN_TIME", "key": "lars_opt_learning_rate_decay_steps", "value": 232397, "metadata": {"file": "/workspace/image_classification/common/fit.py", "lineno": 1194}}
Traceback (most recent call last):
  File "train_imagenet.py", line 236, in <module>
    fit.fit(args, kv, model, initializer, lambda_fnc_dali_get_rec_iter, devs, arg_params, aux_params)
  File "/workspace/image_classification/common/fit.py", line 1331, in fit
    mx.ndarray.waitall()
  File "/opt/mxnet/python/mxnet/ndarray/ndarray.py", line 212, in waitall
    check_call(_LIB.MXNDArrayWaitAll())
  File "/opt/mxnet/python/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/operator/nn/norm_convolution.cu", line 104
MXNetError: No fallback impl for unsupported NormConvolution configuration.
```

**Comment by nv-rborkar** [comment]
Can you specify the GPU configuration used?

**Comment by arjunsuresh** [comment]
It is a single RTX 4090 card.

**Comment by mmarcinkiewicz** [comment]
RN50 won't converge on 1 GPU.
If you want to just try if it runs (and how fast) out need to use `--network resnet-v1b-fl`

**Comment by arjunsuresh** [comment]
Thank you @mmarcinkiewicz That made it work and thanks for letting us know of the convergence issue.
